# Generated by Django 5.2.4 on 2025-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailverification_options_alter_user_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_extra_permissions', to='auth.permission'),
        ),
    ]
