# Generated by Django 5.2.4 on 2026-07-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_data'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE accounts_accessrequest
            DROP COLUMN role_demande;
            """,
            """
            ALTER TABLE accounts_accessrequest
            ADD COLUMN role_demande varchar(50) NOT NULL DEFAULT 'unknown';
            """
        )
    ]
