# Generated by Django 5.2.4 on 2025-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_extra_permissions'),
        ('fosa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wilaya_fk',
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya_fk',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_wilaya', to='fosa.wilaya'),
        ),
    ]
