# Generated by Django 5.2.4 on 2025-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_wilaya_fk_user_wilaya_fk'),
        ('fosa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wilaya_fk',
        ),
        migrations.AddField(
            model_name='user',
            name='wilayas',
            field=models.ManyToManyField(blank=True, related_name='users', to='fosa.wilaya'),
        ),
    ]
