from collections import defaultdict

# Dictionnaires des codes à 2 chiffres 
type_codes = {
    "PS": "01",
    "CS": "02",
    "CH": "03",
    "DRS": "04",
    "Direction centrale": "05",
    "Cabinet Ministre": "06",
    "FONDAMENTAL": "07",
    "Autres": "08"
}


wilaya_codes = {
    "Hodh Chargui": "01",
    "Hodh El Gharbi": "02",
    "Assaba": "03",
    "Gorgol": "04",
    "Brakna": "05",
    "Trarza": "06",
    "Adrar": "07",
    "Dakhlet Nouadhibou": "08",
    "Tagant": "09",
    "Guidimagha": "10",
    "Tiris Zemmour": "11",
    "Inchiri": "12",
    "Nouakchott Ouest": "13",
    "Nouakchott Nord": "14",
    "Nouakchott Sud": "15"
}

moughataa_codes = {
    "Adelbegrou": "01",
    "Amourj": "02",
    "Bassiknou": "03",
    "Djiguenni": "04",
    "N'beiket Lahwach": "05",
    "Néma": "06",
    "Oualata": "07",
    "Timbedra": "08",
    "Aioun": "09",
    "Kobenni": "10",
    "Tamcheket": "11",
    "Tintane": "12",
    "Touil": "13",
    "Barkéol": "14",
    "Boumdeid": "15",
    "Guerou": "16",
    "Kankoussa": "17",
    "Kiffa": "18",
    "Kaédi": "19",
    "Lexeiba1": "20",
    "Maghama": "21",
    "M'Bout": "22",
    "Monguel": "23",
    "Aleg": "24",
    "Bababé": "25",
    "Boghé": "26",
    "Magtalahjar": "27",
    "Male": "28",
    "M'Bagne": "29",
    "Boutilimit": "30",
    "Keur Macène": "31",
    "Mederdra": "32",
    "Ouad Naga": "33",
    "R'Kiz": "34",
    "Rosso": "35",
    "Tekane": "36",
    "Aoujeft": "37",
    "Atar": "38",
    "Chinguitti": "39",
    "Ouadane": "40",
    "Chami": "41",
    "Nouadhibou": "42",
    "Moudjeria": "43",
    "Tichit": "44",
    "Tidjikja": "45",
    "Ghabou": "46",
    "Ould Yengé": "47",
    "Sélibaby": "48",
    "Wompou": "49",
    "Bir Moghrein": "50",
    "F'Deirick": "51",
    "Zoueratt": "52",
    "Akjoujt": "53",
    "Bennechab": "54",
    "Ksar": "55",
    "Sebkha": "56",
    "Tevragh Zeina": "57",
    "Dar Naïm": "58",
    "Teyaret": "59",
    "Toujounine": "60",
    "Arafat": "61",
    "El Mina": "62",
    "Riyad": "63"
}


commune_codes = {
    "Adel Bagrou": "01",
    "ELMESSGOUL": "02",
    "Sivane": "03",
    "Amourj": "01",
    "Bougadoum": "02",
    "Diegui": "03",
    "LGDOUR": "04",
    "OUM ECHEICH": "05",
    "Bassiknou": "01",
    "Dhar": "02",
    "El Megve": "03",
    "Vassala": "04",
    "Aoueinat Zbel": "01",
    "Beneamane1": "02",
    "Djiguenni": "03",
    "El Mebrouk": "04",
    "Feireni": "05",
    "Gasr El Barka": "06",
    "Ghlig Ehel Boyé": "07",
    "N'Beiket Lahwach": "01",
    "Achemim": "01",
    "Agoueinit": "02",
    "Bangou": "03",
    "Beribave": "04",
    "Hassi Etile": "05",
    "Jreif": "06",
    "Mabrouk": "07",
    "Néma": "08",
    "Noual": "09",
    "Oum Avnadech": "10",
    "Elbatene": "01",
    "Oualata": "02",
    "Bousteila": "01",
    "Etouil": "02",
    "Hassi M'Hadi": "03",
    "Koumbi Saleh": "04",
    "Timbedra": "05",
    "Aioun": "01",
    "Beneamane2": "02",
    "Doueirare": "03",
    "Egjert": "04",
    "N'Savenni": "05",
    "Oum Lahyadh": "06",
    "Ten Hamadi": "07",
    "Gougui Zemmal": "01",
    "Hassi Ehl Ahmed Bechne": "02",
    "Koubanni": "03",
    "Leghlig": "04",
    "Modibougou": "05",
    "Timzine": "06",
    "Voullaniya": "07",
    "El Mabrouk": "01",
    "Guetae Teidoume": "02",
    "Radhi": "03",
    "Sava": "04",
    "Tamcheket": "05",
    "Ain Varba": "01",
    "Aweinat Thalle": "02",
    "Devaa": "03",
    "Egharghar": "04",
    "Hassi Abdallah": "05",
    "Tintane": "06",
    "Baghdad": "01",
    "Essett": "02",
    "Lehreijat": "03",
    "Touil": "04",
    "Barkéol": "01",
    "Bou Lahrath": "02",
    "Daghveg": "03",
    "El Ghabra": "04",
    "Gueller": "05",
    "Laweissi": "06",
    "Lebheir": "07",
    "R'Dheidhie": "08",
    "Boumdeid": "01",
    "Hseiy Tin": "02",
    "Lavtah": "03",
    "El Ghaira": "01",
    "Guerou": "02",
    "Kamour": "03",
    "Oudeiy Jrid": "04",
    "Blajmil": "01",
    "Hamed": "02",
    "Kankoussa": "03",
    "Sani": "04",
    "Tenaha": "05",
    "Aghorat": "01",
    "El Melgue": "02",
    "Kiffa": "03",
    "Kouroudjel": "04",
    "Legrane": "05",
    "Nouamlein": "06",
    "Djewol": "01",
    "Kaédi": "02",
    "Nere Walo": "03",
    "Tifondé Civé": "04",
    "Tokomadji": "05",
    "Betengal": "01",
    "Ganki": "02",
    "Lexeiba1": "03",
    "Talhaya": "04",
    "Beileguet Litam": "01",
    "Daw": "02",
    "Dolol Cive": "03",
    "Maghama": "04",
    "Sagny": "05",
    "Toulel": "06",
    "Vrea Litame": "07",
    "Wali Djantang": "08",
    "Chelkhet Tiyab": "01",
    "Edebaye Ehel Guelaye": "02",
    "Lahrach": "03",
    "M'Bout": "04",
    "N'Djadjbenni Gandega": "05",
    "Soufa": "06",
    "Targuent Ehl Moulaye Ely": "07",
    "Tikobra": "08",
    "Voum Legleite": "09",
    "Azgueleme Tiyab": "01",
    "Bathet meit": "02",
    "Boukel": "03",
    "Melzem Teichet": "04",
    "Monguel": "05",
    "Aghchourguit": "01",
    "Aleg": "02",
    "Bouhdide": "03",
    "Cheggar": "04",
    "Aere M'Bar": "01",
    "Bababé": "02",
    "El Verae": "03",
    "Boghé": "01",
    "Dar EL Aviye": "02",
    "Dar El Barke": "03",
    "Ould Biram": "04",
    "Djonabe": "01",
    "Magtalahjar": "02",
    "Ouad Emmour": "03",
    "Sangrave": "04",
    "Bouratt": "01",
    "Djellewar": "02",
    "Elwad lebied": "03",
    "Male": "04",
    "Roumed": "05",
    "Bagodine": "01",
    "Edebaye El Hejaj": "02",
    "M'Bagne": "03",
    "Niabina": "04",
    "Ajoueir": "01",
    "Boutilimit": "02",
    "El Mouyessar": "03",
    "Elb Adress": "04",
    "Nebaghiya": "05",
    "N'Teichet": "06",
    "Tenghadej": "07",
    "Keur Macène": "01",
    "M'Balal": "02",
    "N'Diago": "03",
    "Beir Taouress": "01",
    "El Khat": "02",
    "Mederdra": "03",
    "Taguilalet": "04",
    "Tiguent": "05",
    "Aouleyigat": "01",
    "El Ariye": "02",
    "Ouad Naga": "03",
    "Bareine": "01",
    "Boutalhaye": "02",
    "R'Kiz": "03",
    "Jedrel Mohguen": "01",
    "Rosso": "02",
    "Chemame": "01",
    "Lexeiba2": "02",
    "teichtayat": "03",
    "Tekane": "04",
    "Aoujeft": "01",
    "El Medah": "02",
    "Maeden": "03",
    "N'Teirguent": "04",
    "Ain Ehel Taya": "01",
    "Atar": "02",
    "Choum": "03",
    "Tawaz": "04",
    "Ain Savra": "01",
    "Chinguitti": "02",
    "Ouadane": "03",
    "Chami": "01",
    "Nouamghar": "02",
    "Tmeimichat": "03",
    "Boulenouar": "01",
    "Inal": "02",
    "Nouadhibou": "03",
    "Moudjeria": "01",
    "Soudoud": "02",
    "Tamourt Naaj": "03",
    "Lekhcheb": "01",
    "Tichit": "02",
    "Boubacar Ben Amer": "01",
    "El Wahat (Rachid)": "02",
    "Lehsira": "03",
    "Nimlane": "04",
    "Tidjikja": "05",
    "Baydjam": "01",
    "Douguentourou": "02",
    "Echleikha": "03",
    "Ghabou": "04",
    "Gouraye": "05",
    "Souvi": "06",
    "Bouanz": "01",
    "Dafort": "02",
    "Leaweinat": "03",
    "Leboully": "04",
    "Lehraj": "05",
    "Ould Yengé": "06",
    "Tektake": "07",
    "Hassi Chegar": "01",
    "Ould M'Bonny": "02",
    "Sélibaby": "03",
    "Tachout": "04",
    "Arr": "02",
    "Ejar": "03",
    "Sagné": "04",
    "Wompou": "05",
    "Bir Moghrein": "01",
    "F'Deirick": "01",
    "Zoueratt": "01",
    "Akjoujt": "01",
    "Bennechab": "01",
    "M'heijrat": "02",
    "Ksar": "01",
    "Sebkha": "01",
    "Tevragh Zeina": "01",
    "Dar Naïm": "01",
    "Teyaret": "01",
    "Toujounine": "01",
    "Arafat": "01",
    "El Mina": "01",
    "Riyad": "01"
}

