# Generated by Django 5.2.4 on 2025-09-15 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['moughataa__wilaya__nom', 'moughataa__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['wilaya__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FOSA',
            fields=[
                ('nom_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (Français)')),
                ('nom_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (Arabe)')),
                ('type', models.CharField(blank=True, choices=[('PS', 'Poste de Santé'), ('CS', 'Centre de Santé'), ('CH', 'Centre hospitalier'), ('DRS', 'Direction Régionale de Santé'), ('DAF', 'Direction Administrative et Financière')], max_length=50, null=True)),
                ('code_etablissement', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(default='Inconnu', max_length=100)),
                ('moughataa', models.CharField(default='Inconnu', max_length=100)),
                ('wilaya', models.CharField(default='Inconnu', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('commune_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='fosa.commune')),
                ('moughataa_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='fosa.moughataa')),
                ('wilaya_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='fosa.wilaya')),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='FOSAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('DELETE', 'Suppression')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='fosa.fosa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='moughataa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='fosa.moughataa'),
        ),
        migrations.AddField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moughataas', to='fosa.wilaya'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['nom', 'moughataa'], name='fosa_commun_nom_a5290b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together={('nom', 'moughataa')},
        ),
        migrations.AddIndex(
            model_name='moughataa',
            index=models.Index(fields=['nom', 'wilaya'], name='fosa_mougha_nom_aa02b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moughataa',
            unique_together={('nom', 'wilaya')},
        ),
        migrations.AddIndex(
            model_name='fosa',
            index=models.Index(fields=['code_etablissement'], name='fosa_fosa_code_et_2b3e13_idx'),
        ),
    ]
