# Generated by Django 5.2.8 on 2026-04-01 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='Code')),
            ],
            options={
                'ordering': ['moughataa__wilaya__nom', 'moughataa__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled_fields', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Moughataa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='Code')),
            ],
            options={
                'ordering': ['wilaya__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de structure',
                'verbose_name_plural': 'Types de structure',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Code')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FOSA',
            fields=[
                ('code_etablissement', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('structure', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('PS', 'Poste de Santé'), ('CS', 'Centre de Santé'), ('CH', 'Centre hospitalier'), ('DRS', 'Direction Régionale de Santé'), ('DAF', 'Direction Administrative et Financière'), ('FOND', 'FOND'), ('AUTRE', 'Autre')], max_length=50, null=True)),
                ('commune', models.CharField(default='Inconnu', max_length=100)),
                ('moughataa', models.CharField(default='Inconnu', max_length=100)),
                ('wilaya', models.CharField(default='Inconnu', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coordonnee_gps', models.CharField(blank=True, max_length=128, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('etat', models.CharField(blank=True, max_length=64, null=True)),
                ('etat_batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('cloture', models.BooleanField(blank=True, null=True)),
                ('electricite', models.BooleanField(blank=True, null=True)),
                ('internet', models.BooleanField(blank=True, null=True)),
                ('eau', models.BooleanField(blank=True, null=True)),
                ('cdf', models.BooleanField(blank=True, null=True)),
                ('equipement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_de_construction', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fosa_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('fosa_plus_proche', models.CharField(blank=True, max_length=255, null=True)),
                ('prestation_service', models.JSONField(blank=True, default=list, null=True)),
                ('service_manquant', models.JSONField(blank=True, default=list, null=True)),
                ('besoins', models.CharField(blank=True, max_length=255, null=True)),
                ('pourcentage_activite', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('bailleur', models.TextField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('commune_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='fosa.commune')),
                ('moughataa_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='fosa.moughataa')),
                ('type_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fosas', to='fosa.typestructure', verbose_name='Type normatif')),
                ('wilaya_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fosas', to='fosa.wilaya')),
            ],
            options={
                'ordering': ['structure'],
            },
        ),
        migrations.CreateModel(
            name='FOSAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('DELETE', 'Suppression')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='fosa.fosa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='moughataa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='fosa.moughataa'),
        ),
        migrations.CreateModel(
            name='PersonnelStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_poste', models.CharField(max_length=150)),
                ('nombre_reel', models.PositiveIntegerField(default=0)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personnels', to='fosa.fosa')),
            ],
            options={
                'verbose_name': 'Personnel réel de la structure',
                'verbose_name_plural': 'Personnel réel des structures',
            },
        ),
        migrations.CreateModel(
            name='ServiceStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=False)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='fosa.fosa')),
            ],
            options={
                'verbose_name': 'Service offert par la structure',
                'verbose_name_plural': 'Services offerts par les structures',
            },
        ),
        migrations.CreateModel(
            name='NormeStructureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_min', models.PositiveIntegerField(blank=True, null=True)),
                ('population_max', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_min_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('type_structure', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='norme_info', to='fosa.typestructure')),
            ],
        ),
        migrations.CreateModel(
            name='NormeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=200)),
                ('obligatoire', models.BooleanField(default=True)),
                ('type_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normes_services', to='fosa.typestructure')),
            ],
            options={
                'verbose_name': 'Norme de service',
                'verbose_name_plural': 'Normes de service',
            },
        ),
        migrations.CreateModel(
            name='NormePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_poste', models.CharField(max_length=150)),
                ('nombre_minimal', models.PositiveIntegerField(default=1)),
                ('type_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normes_personnel', to='fosa.typestructure')),
            ],
            options={
                'verbose_name': 'Norme de personnel',
                'verbose_name_plural': 'Normes de personnel',
            },
        ),
        migrations.CreateModel(
            name='NormeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=200)),
                ('quantite_minimale', models.PositiveIntegerField(default=1)),
                ('type_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normes_materiel', to='fosa.typestructure')),
            ],
            options={
                'verbose_name': 'Norme de matériel',
                'verbose_name_plural': 'Normes de matériel',
            },
        ),
        migrations.AddField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moughataas', to='fosa.wilaya'),
        ),
        migrations.CreateModel(
            name='MaladieReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_start', models.DateField(blank=True, db_index=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('cas_suspects', models.PositiveIntegerField(blank=True, null=True)),
                ('deces', models.PositiveIntegerField(blank=True, null=True)),
                ('cas_preleves', models.PositiveIntegerField(blank=True, null=True)),
                ('cas_testes', models.PositiveIntegerField(blank=True, null=True)),
                ('cas_confirmes', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fosa.maladie')),
                ('moughataa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fosa.moughataa')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fosa.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=200)),
                ('quantite_reelle', models.PositiveIntegerField(default=0)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='materiels', to='fosa.fosa')),
            ],
            options={
                'verbose_name': 'Matériel de la structure',
                'verbose_name_plural': 'Matériel des structures',
                'unique_together': {('structure', 'nom_materiel')},
            },
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['moughataa', 'nom'], name='fosa_commun_moughat_8cda37_idx'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('moughataa', 'nom'), name='uniq_commune_nom_in_moughataa'),
        ),
        migrations.AlterUniqueTogether(
            name='personnelstructure',
            unique_together={('structure', 'intitule_poste')},
        ),
        migrations.AlterUniqueTogether(
            name='servicestructure',
            unique_together={('structure', 'nom_service')},
        ),
        migrations.AlterUniqueTogether(
            name='normeservice',
            unique_together={('type_structure', 'nom_service')},
        ),
        migrations.AlterUniqueTogether(
            name='normepersonnel',
            unique_together={('type_structure', 'intitule_poste')},
        ),
        migrations.AlterUniqueTogether(
            name='normemateriel',
            unique_together={('type_structure', 'nom_materiel')},
        ),
        migrations.AddIndex(
            model_name='moughataa',
            index=models.Index(fields=['wilaya', 'nom'], name='fosa_mougha_wilaya__ed3d0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='moughataa',
            constraint=models.UniqueConstraint(fields=('wilaya', 'nom'), name='uniq_moughataa_nom_in_wilaya'),
        ),
        migrations.AddIndex(
            model_name='maladiereport',
            index=models.Index(fields=['week_start'], name='fosa_maladi_week_st_b851e4_idx'),
        ),
        migrations.AddIndex(
            model_name='maladiereport',
            index=models.Index(fields=['is_archived'], name='fosa_maladi_is_arch_ed967e_idx'),
        ),
        migrations.AddIndex(
            model_name='maladiereport',
            index=models.Index(fields=['week_start', 'is_archived'], name='fosa_maladi_week_st_ac6e3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='maladiereport',
            constraint=models.UniqueConstraint(fields=('date', 'wilaya', 'moughataa', 'maladie'), name='uniq_report_per_day_area_maladie'),
        ),
        migrations.AddIndex(
            model_name='fosa',
            index=models.Index(fields=['code_etablissement'], name='fosa_fosa_code_et_2b3e13_idx'),
        ),
        migrations.AddIndex(
            model_name='fosa',
            index=models.Index(fields=['wilaya_fk', 'moughataa_fk', 'commune_fk'], name='fosa_fosa_wilaya__e0cb85_idx'),
        ),
    ]
