# Generated by Django 5.2.8 on 2026-07-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maladiereport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumis'), ('validated', 'Validé'), ('shown', 'Affiché')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
