# Generated by Django 5.2.4 on 2025-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moughataa',
            name='fosa_mougha_nom_aa02b8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='moughataa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moughataa',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='nom',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AddIndex(
            model_name='moughataa',
            index=models.Index(fields=['wilaya', 'nom'], name='fosa_mougha_wilaya__ed3d0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='moughataa',
            constraint=models.UniqueConstraint(fields=('wilaya', 'nom'), name='uniq_moughataa_nom_in_wilaya'),
        ),
    ]
