# Generated by Django 5.2.4 on 2026-07-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='is_epidemic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maladie',
            name='seuil_alerte',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='fosa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maladie_reports', to='fosa.fosa', verbose_name='FOSA'),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='status',
            field=models.CharField(choices=[('sent', 'Envoyé'), ('validated', 'Validé'), ('alert', 'Alerte'), ('pending', 'En attente')], default='sent', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maladie_reports', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
    ]
