# Generated by Django 5.2.8 on 2026-07-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0002_maladiereport_status_maladiereport_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladiereport',
            name='shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
