# Generated by Django 5.2.4 on 2026-07-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0002_maladie_is_epidemic_maladie_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='can_report_individually',
            field=models.BooleanField(default=False, verbose_name='Peut être signalée individuellement'),
        ),
        migrations.AddField(
            model_name='maladie',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom en arabe'),
        ),
    ]
