# Generated by Django 5.2.4 on 2025-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0002_remove_moughataa_fosa_mougha_nom_aa02b8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moughataa',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Code'),
        ),
    ]
