# Generated by Django 5.2.4 on 2025-09-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0003_alter_moughataa_code_alter_wilaya_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commune',
            name='fosa_commun_nom_a5290b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='commune',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commune',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['moughataa', 'nom'], name='fosa_commun_moughat_8cda37_idx'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('moughataa', 'nom'), name='uniq_commune_nom_in_moughataa'),
        ),
    ]
