# Generated by Django 5.2.4 on 2025-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0004_remove_commune_fosa_commun_nom_a5290b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosa',
            name='type',
            field=models.CharField(blank=True, choices=[('PS', 'Poste de Santé'), ('CS', 'Centre de Santé'), ('CH', 'Centre hospitalier'), ('DRS', 'Direction Régionale de Santé'), ('DAF', 'Direction Administrative et Financière'), ('AUTRE', 'Autre')], max_length=50, null=True),
        ),
    ]
