# Generated by Django 5.2.4 on 2025-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0005_alter_fosa_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosa',
            name='type',
            field=models.CharField(blank=True, choices=[('PS', 'Poste de Santé'), ('CS', 'Centre de Santé'), ('CH', 'Centre hospitalier'), ('DRS', 'Direction Régionale de Santé'), ('DAF', 'Direction Administrative et Financière'), ('FOND', 'FOND'), ('AUTRE', 'Autre')], max_length=50, null=True),
        ),
    ]
