# Generated by Django 5.2.8 on 2026-01-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0006_alter_fosa_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled_fields', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MaladieReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cas_suspects', models.PositiveIntegerField(blank=True, null=True)),
                ('deces', models.PositiveIntegerField(blank=True, null=True)),
                ('cas_preleves', models.PositiveIntegerField(blank=True, null=True)),
                ('cas_testes', models.PositiveIntegerField(blank=True, null=True)),
                ('cas_confirmes', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fosa.maladie')),
                ('moughataa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fosa.moughataa')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fosa.wilaya')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'wilaya', 'moughataa', 'maladie'), name='uniq_report_per_day_area_disease')],
            },
        ),
    ]
