# Generated by Django 5.2.8 on 2026-01-19 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0007_maladie_maladiereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=200)),
                ('quantite_reelle', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Matériel de la structure',
                'verbose_name_plural': 'Matériel des structures',
            },
        ),
        migrations.CreateModel(
            name='NormeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=200)),
                ('quantite_minimale', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Norme de matériel',
                'verbose_name_plural': 'Normes de matériel',
            },
        ),
        migrations.CreateModel(
            name='NormePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_poste', models.CharField(max_length=150)),
                ('nombre_minimal', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Norme de personnel',
                'verbose_name_plural': 'Normes de personnel',
            },
        ),
        migrations.CreateModel(
            name='NormeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=200)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Norme de service',
                'verbose_name_plural': 'Normes de service',
            },
        ),
        migrations.CreateModel(
            name='PersonnelStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_poste', models.CharField(max_length=150)),
                ('nombre_reel', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Personnel réel de la structure',
                'verbose_name_plural': 'Personnel réel des structures',
            },
        ),
        migrations.CreateModel(
            name='ServiceStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Service offert par la structure',
                'verbose_name_plural': 'Services offerts par les structures',
            },
        ),
        migrations.CreateModel(
            name='StructureSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('structure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la structure')),
                ('type_brut', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type brut (fichier source)')),
                ('etat', models.CharField(blank=True, max_length=64, null=True, verbose_name='État de fonctionnalité')),
                ('nom_ar', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nom en arabe')),
                ('coordonnee_gps', models.CharField(blank=True, max_length=128, null=True, verbose_name='Coordonnées')),
                ('responsable', models.CharField(blank=True, max_length=128, null=True, verbose_name='Responsable')),
                ('departement', models.CharField(default='santé', editable=False, max_length=64)),
                ('etat_batiment', models.CharField(blank=True, max_length=100, null=True)),
                ('etat_general', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('moughataa', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('date_de_creation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_de_construction', models.CharField(blank=True, max_length=100, null=True)),
                ('cloture', models.BooleanField(blank=True, null=True)),
                ('electricite', models.BooleanField(blank=True, null=True)),
                ('internet', models.BooleanField(blank=True, null=True)),
                ('eau', models.BooleanField(blank=True, null=True)),
                ('cdf', models.BooleanField(blank=True, null=True)),
                ('equipement', models.BooleanField(blank=True, null=True)),
                ('fosa_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('fosa_plus_proche', models.CharField(blank=True, max_length=255, null=True)),
                ('type_construction', models.CharField(blank=True, max_length=255, null=True)),
                ('prestation_service', models.CharField(blank=True, max_length=255, null=True)),
                ('service_manquant', models.CharField(blank=True, max_length=255, null=True)),
                ('besoins', models.CharField(blank=True, max_length=255, null=True)),
                ('pma', models.CharField(blank=True, max_length=255, null=True)),
                ('pca', models.CharField(blank=True, max_length=255, null=True)),
                ('pourcentage_activite', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('bailleur', models.TextField(blank=True, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Structure de santé',
                'verbose_name_plural': 'Structures de santé',
                'ordering': ['wilaya', 'moughataa', 'commune', 'structure'],
            },
        ),
        migrations.CreateModel(
            name='TypeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de structure',
                'verbose_name_plural': 'Types de structure',
            },
        ),
        migrations.RemoveConstraint(
            model_name='maladiereport',
            name='uniq_report_per_day_area_disease',
        ),
        migrations.AddConstraint(
            model_name='maladiereport',
            constraint=models.UniqueConstraint(fields=('date', 'wilaya', 'moughataa', 'maladie'), name='uniq_report_per_day_area_maladie'),
        ),
        migrations.AddField(
            model_name='structuresante',
            name='commune_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures_sante', to='fosa.commune'),
        ),
        migrations.AddField(
            model_name='structuresante',
            name='moughataa_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures_sante', to='fosa.moughataa'),
        ),
        migrations.AddField(
            model_name='structuresante',
            name='wilaya_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structures_sante', to='fosa.wilaya'),
        ),
        migrations.AddField(
            model_name='servicestructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fosa.structuresante'),
        ),
        migrations.AddField(
            model_name='personnelstructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='fosa.structuresante'),
        ),
        migrations.AddField(
            model_name='materielstructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='fosa.structuresante'),
        ),
        migrations.AddField(
            model_name='structuresante',
            name='type_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='fosa.typestructure'),
        ),
        migrations.AddField(
            model_name='normeservice',
            name='type_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normes_services', to='fosa.typestructure'),
        ),
        migrations.AddField(
            model_name='normepersonnel',
            name='type_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normes_personnel', to='fosa.typestructure'),
        ),
        migrations.AddField(
            model_name='normemateriel',
            name='type_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normes_materiel', to='fosa.typestructure'),
        ),
        migrations.AlterUniqueTogether(
            name='servicestructure',
            unique_together={('structure', 'nom_service')},
        ),
        migrations.AlterUniqueTogether(
            name='personnelstructure',
            unique_together={('structure', 'intitule_poste')},
        ),
        migrations.AlterUniqueTogether(
            name='materielstructure',
            unique_together={('structure', 'nom_materiel')},
        ),
        migrations.AddIndex(
            model_name='structuresante',
            index=models.Index(fields=['wilaya', 'moughataa', 'commune'], name='fosa_struct_wilaya_3bdcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='structuresante',
            index=models.Index(fields=['code'], name='fosa_struct_code_0207d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='normeservice',
            unique_together={('type_structure', 'nom_service')},
        ),
        migrations.AlterUniqueTogether(
            name='normepersonnel',
            unique_together={('type_structure', 'intitule_poste')},
        ),
        migrations.AlterUniqueTogether(
            name='normemateriel',
            unique_together={('type_structure', 'nom_materiel')},
        ),
    ]
