# Generated by Django 5.2.8 on 2026-01-19 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0008_materielstructure_normemateriel_normepersonnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormeStructureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_min', models.PositiveIntegerField(blank=True, null=True)),
                ('population_max', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_min_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('type_structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='norme_info', to='fosa.typestructure')),
            ],
        ),
    ]
