# Generated by Django 5.2.8 on 2026-01-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0009_normestructureinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuresante',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='remarque',
        ),
    ]
