# Generated by Django 5.2.8 on 2026-01-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0010_remove_structuresante_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuresante',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant lisible, ex : FOSA-000001', max_length=20, null=True, unique=True),
        ),
    ]
