# Generated by Django 5.2.8 on 2026-01-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0011_alter_structuresante_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuresante',
            name='type_brut',
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='type_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='fosa.typestructure', verbose_name='Type normatif'),
        ),
    ]
