# Generated by Django 5.2.8 on 2026-01-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0012_remove_structuresante_type_brut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuresante',
            options={'ordering': ['wilaya_fk__nom', 'moughataa_fk__nom', 'commune_fk__nom', 'structure'], 'verbose_name': 'Structure de santé', 'verbose_name_plural': 'Structures de santé'},
        ),
        migrations.RemoveIndex(
            model_name='structuresante',
            name='fosa_struct_wilaya_3bdcc9_idx',
        ),
        migrations.RemoveIndex(
            model_name='structuresante',
            name='fosa_struct_code_0207d8_idx',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='date_de_creation',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='etat_general',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='moughataa',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='pca',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='pma',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='type_construction',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='wilaya',
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='equipement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
