# Generated by Django 5.2.8 on 2026-01-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0013_alter_structuresante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuresante',
            name='prestation_service',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='service_manquant',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
