# Generated by Django 5.2.8 on 2026-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0014_alter_structuresante_prestation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuresante',
            name='prestation_service',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='service_manquant',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
