# Generated by Django 5.2.8 on 2026-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0015_alter_structuresante_prestation_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladiereport',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='maladiereport',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='structuresante',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='maladiereport',
            index=models.Index(fields=['week_start'], name='fosa_maladi_week_st_b851e4_idx'),
        ),
        migrations.AddIndex(
            model_name='maladiereport',
            index=models.Index(fields=['is_archived'], name='fosa_maladi_is_arch_ed967e_idx'),
        ),
        migrations.AddIndex(
            model_name='maladiereport',
            index=models.Index(fields=['week_start', 'is_archived'], name='fosa_maladi_week_st_ac6e3e_idx'),
        ),
    ]
