# Generated by Django 5.2.4 on 2026-03-24 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0016_maladiereport_is_archived_maladiereport_week_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuresante',
            name='commune_fk',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='moughataa_fk',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='type_structure',
        ),
        migrations.RemoveField(
            model_name='structuresante',
            name='wilaya_fk',
        ),
        migrations.AlterField(
            model_name='personnelstructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personnels', to='fosa.fosa'),
        ),
        migrations.AlterField(
            model_name='servicestructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='fosa.fosa'),
        ),
        migrations.AlterField(
            model_name='materielstructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='materiels', to='fosa.fosa'),
        ),
        migrations.AlterModelOptions(
            name='fosa',
            options={'ordering': ['structure']},
        ),
        migrations.AddField(
            model_name='fosa',
            name='bailleur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='besoins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='cdf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='cloture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='coordonnee_gps',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fosa',
            name='date_de_construction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='eau',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='electricite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='equipement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='etat',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='etat_batiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='fosa_plus_proche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='fosa_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='internet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='pourcentage_activite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='prestation_service',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='service_manquant',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='structure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fosa',
            name='type_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fosas', to='fosa.typestructure', verbose_name='Type normatif'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='nom_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normestructureinfo',
            name='type_structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='norme_info', to='fosa.typestructure'),
        ),
        migrations.AddIndex(
            model_name='fosa',
            index=models.Index(fields=['wilaya_fk', 'moughataa_fk', 'commune_fk'], name='fosa_fosa_wilaya__e0cb85_idx'),
        ),
        migrations.DeleteModel(
            name='StructureSante',
        ),
    ]
