# Generated by Django 5.2.4 on 2026-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0017_remove_structuresante_commune_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fosa',
            name='code_etablissement',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
