# Generated by Django 5.2.4 on 2026-03-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0018_fosa_id_alter_fosa_code_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosa',
            name='code_etablissement',
            field=models.CharField(max_length=100),
        ),
    ]
