# Generated by Django 5.2.4 on 2026-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fosa', '0020_alter_fosa_code_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosa',
            name='id',
        ),
        migrations.AlterField(
            model_name='fosa',
            name='code_etablissement',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
